config/routes.rb
Sigco::Application.routes.draw do
  
  resources :materiales_auditoria

  resources :auditoria

  resources :auditors

  resources :visita

  resources :materials

  resources :inscripcions

  resources :materia_cursos

  resources :profesors

  resources :materia

  resources :cursos

  resources :administradors

  resources :fichas

  root 'vecinos#index'

  resources :vecinos

  get 'facturas' => 'facturas#index'
  get 'facturas/create' => 'facturas#new'
  get 'facturas/:id' => 'facturas#show', :as => :factura
  post 'facturas' => 'facturas#create'

end

app/models/administrador.rb
class Administrador < ActiveRecord::Base

	validates_presence_of :nombre

	has_many :fichas

end

app/models/auditor.rb
class Auditor < ActiveRecord::Base
	validates_presence_of :nombre
    validates_presence_of :apellidos
    validates_presence_of :cif
    validates_presence_of :nombre_empresa
    validates_presence_of :direccion_empresa
    validates_presence_of :telefono

    has_many :auditoria

end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base
	belongs_to :auditor

end

app/models/curso.rb
class Curso < ActiveRecord::Base

	has_many :materia_curso
	has_many :materia, :through => :materia_curso

	has_many :inscripcion
	has_many :vecinos, :through => :inscripcion

end

app/models/factura.rb
class Factura < ActiveRecord::Base

	has_many :fichas
	belongs_to :vecino

end

app/models/ficha.rb
class Ficha < ActiveRecord::Base

	belongs_to :vecino
	belongs_to :factura
	belongs_to :administrador

end

app/models/inscripcion.rb
class Inscripcion < ActiveRecord::Base
	belongs_to :vecino
	belongs_to :curso
end

app/models/materia_curso.rb
class MateriaCurso < ActiveRecord::Base

	belongs_to :materium
	belongs_to :curso

end

app/models/material.rb
class Material < ActiveRecord::Base
	
end

app/models/materium.rb
class Materium < ActiveRecord::Base

	has_many :materia_cursos
	has_many :cursos, :through => :materia_cursos
	belongs_to :profesor

end

app/models/profesor.rb
class Profesor < ActiveRecord::Base

	has_many :materias

	def nombre_completo
		self.nombre + ' ' + self.apellidos
	end

end

app/models/vecino.rb
class Vecino < ActiveRecord::Base

	validates_presence_of :DNI
	validates_presence_of :nombre
	validates_presence_of :apellidos
	validates_presence_of :direccion
	validates_presence_of :ciudad
	validates_presence_of :cod_postal
	validates_presence_of :telefono

	has_many :facturas
	has_many :fichas

	has_many :inscripcion
	has_many :cursos, :through => :inscripcion

	# Methods
	
	def nombre_completo
		self.nombre + ' ' + self.apellidos
	end

end

app/models/visitum.rb
class Visitum < ActiveRecord::Base

	belongs_to :auditor

end

app/controllers/profesors_controller.rb
class ProfesorsController < ApplicationController
  before_action :set_profesor, only: [:show, :edit, :update, :destroy]

  # GET /profesors
  # GET /profesors.json
  def index
    @profesors = Profesor.all
  end

  # GET /profesors/1
  # GET /profesors/1.json
  def show
  end

  # GET /profesors/new
  def new
    @profesor = Profesor.new
  end

  # GET /profesors/1/edit
  def edit
  end

  # POST /profesors
  # POST /profesors.json
  def create
    @profesor = Profesor.new(profesor_params)

    respond_to do |format|
      if @profesor.save
        format.html { redirect_to @profesor, notice: 'Profesor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profesor }
      else
        format.html { render action: 'new' }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profesors/1
  # PATCH/PUT /profesors/1.json
  def update
    respond_to do |format|
      if @profesor.update(profesor_params)
        format.html { redirect_to @profesor, notice: 'Profesor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesors/1
  # DELETE /profesors/1.json
  def destroy
    @profesor.destroy
    respond_to do |format|
      format.html { redirect_to profesors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesor
      @profesor = Profesor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profesor_params
      params.require(:profesor).permit(:nombre, :apellidos, :direccion, :telefono, :sueldo)
    end
end

app/helpers/auditoria_helper.rb
module AuditoriaHelper
end

app/helpers/auditors_helper.rb
module AuditorsHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/helpers/vecinos_helper.rb
module VecinosHelper
end

app/helpers/visita_helper.rb
module VisitaHelper
end

app/views/profesors/_form.html.haml
= form_for @profesor do |f|
  - if @profesor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@profesor.errors.count, "error")} prohibited this profesor from being saved:"
      %ul
        - @profesor.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nombre
    = f.text_field :nombre
  .field
    = f.label :apellidos
    = f.text_field :apellidos
  .field
    = f.label :direccion
    = f.text_field :direccion
  .field
    = f.label :telefono
    = f.text_field :telefono
  .field
    = f.label :sueldo
    = f.text_field :sueldo
  .actions
    = f.submit 'Save'

app/views/profesors/edit.html.haml
%h1 Editing profesor

= render 'form'

= link_to 'Show', @profesor
\|
= link_to 'Back', profesors_path

app/views/profesors/index.html.haml
%h1 Listing profesors

%table
  %tr
    %th Nombre
    %th Apellidos
    %th Direccion
    %th Telefono
    %th Sueldo
    %th
    %th
    %th

  - @profesors.each do |profesor|
    %tr
      %td= profesor.nombre
      %td= profesor.apellidos
      %td= profesor.direccion
      %td= profesor.telefono
      %td= profesor.sueldo
      %td= link_to 'Show', profesor
      %td= link_to 'Edit', edit_profesor_path(profesor)
      %td= link_to 'Destroy', profesor, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profesor', new_profesor_path

app/views/profesors/new.html.haml
%h1 New profesor

= render 'form'

= link_to 'Back', profesors_path

app/views/profesors/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @profesor.nombre
%p
  %b Apellidos:
  = @profesor.apellidos
%p
  %b Direccion:
  = @profesor.direccion
%p
  %b Telefono:
  = @profesor.telefono
%p
  %b Sueldo:
  = @profesor.sueldo

= link_to 'Edit', edit_profesor_path(@profesor)
\|
= link_to 'Back', profesors_path