config/routes.rb
Sigco::Application.routes.draw do
  
  resources :materiales_auditoria

  resources :auditoria

  resources :auditors

  resources :visita

  resources :materials

  resources :inscripcions

  resources :materia_cursos

  resources :profesors

  resources :materia

  resources :cursos

  resources :administradors

  resources :fichas

  root 'vecinos#index'

  resources :vecinos

  get 'facturas' => 'facturas#index'
  get 'facturas/create' => 'facturas#new'
  get 'facturas/:id' => 'facturas#show', :as => :factura
  post 'facturas' => 'facturas#create'

end

app/models/administrador.rb
class Administrador < ActiveRecord::Base

	validates_presence_of :nombre

	has_many :fichas

end

app/models/auditor.rb
class Auditor < ActiveRecord::Base
	validates_presence_of :nombre
    validates_presence_of :apellidos
    validates_presence_of :cif
    validates_presence_of :nombre_empresa
    validates_presence_of :direccion_empresa
    validates_presence_of :telefono

    has_many :auditoria

end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base
	belongs_to :auditor

end

app/models/curso.rb
class Curso < ActiveRecord::Base

	has_many :materia_curso
	has_many :materia, :through => :materia_curso

	has_many :inscripcion
	has_many :vecinos, :through => :inscripcion

end

app/models/factura.rb
class Factura < ActiveRecord::Base

	has_many :fichas
	belongs_to :vecino

end

app/models/ficha.rb
class Ficha < ActiveRecord::Base

	belongs_to :vecino
	belongs_to :factura
	belongs_to :administrador

end

app/models/inscripcion.rb
class Inscripcion < ActiveRecord::Base
	belongs_to :vecino
	belongs_to :curso
end

app/models/materia_curso.rb
class MateriaCurso < ActiveRecord::Base

	belongs_to :materium
	belongs_to :curso

end

app/models/material.rb
class Material < ActiveRecord::Base
	
end

app/models/materium.rb
class Materium < ActiveRecord::Base

	has_many :materia_cursos
	has_many :cursos, :through => :materia_cursos
	belongs_to :profesor

end

app/models/profesor.rb
class Profesor < ActiveRecord::Base

	has_many :materias

	def nombre_completo
		self.nombre + ' ' + self.apellidos
	end

end

app/models/vecino.rb
class Vecino < ActiveRecord::Base

	validates_presence_of :DNI
	validates_presence_of :nombre
	validates_presence_of :apellidos
	validates_presence_of :direccion
	validates_presence_of :ciudad
	validates_presence_of :cod_postal
	validates_presence_of :telefono

	has_many :facturas
	has_many :fichas

	has_many :inscripcion
	has_many :cursos, :through => :inscripcion

	# Methods
	
	def nombre_completo
		self.nombre + ' ' + self.apellidos
	end

end

app/models/visitum.rb
class Visitum < ActiveRecord::Base

	belongs_to :auditor

end

app/controllers/materia_cursos_controller.rb
class MateriaCursosController < ApplicationController
  before_action :set_materia_curso, only: [:show, :edit, :update, :destroy]

  # GET /materia_cursos
  # GET /materia_cursos.json
  def index
    @materia_cursos = MateriaCurso.all
  end

  # GET /materia_cursos/1
  # GET /materia_cursos/1.json
  def show
  end

  # GET /materia_cursos/new
  def new
    @materia_curso = MateriaCurso.new
  end

  # GET /materia_cursos/1/edit
  def edit
  end

  # POST /materia_cursos
  # POST /materia_cursos.json
  def create
    @materia_curso = MateriaCurso.new(materia_curso_params)

    respond_to do |format|
      if @materia_curso.save
        format.html { redirect_to @materia_curso, notice: 'Materia curso was successfully created.' }
        format.json { render action: 'show', status: :created, location: @materia_curso }
      else
        format.html { render action: 'new' }
        format.json { render json: @materia_curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materia_cursos/1
  # PATCH/PUT /materia_cursos/1.json
  def update
    respond_to do |format|
      if @materia_curso.update(materia_curso_params)
        format.html { redirect_to @materia_curso, notice: 'Materia curso was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @materia_curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materia_cursos/1
  # DELETE /materia_cursos/1.json
  def destroy
    @materia_curso.destroy
    respond_to do |format|
      format.html { redirect_to materia_cursos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materia_curso
      @materia_curso = MateriaCurso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def materia_curso_params
      params.require(:materia_curso).permit(:materium_id, :curso_id)
    end
end

app/helpers/auditoria_helper.rb
module AuditoriaHelper
end

app/helpers/auditors_helper.rb
module AuditorsHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/materia_cursos_helper.rb
module MateriaCursosHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/vecinos_helper.rb
module VecinosHelper
end

app/helpers/visita_helper.rb
module VisitaHelper
end

app/views/materia_cursos/_form.html.haml
= form_for @materia_curso do |f|
  - if @materia_curso.errors.any?
    #error_explanation
      %h2= "#{pluralize(@materia_curso.errors.count, "error")} prohibited this materia_curso from being saved:"
      %ul
        - @materia_curso.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :materium_id
    = f.collection_select :materium_id, Materium.all, :id, :nombre
  .field
    = f.label :curso_id
    = f.collection_select :curso_id, Curso.all, :id, :nombre
  .actions
    = f.submit 'Save'

app/views/materia_cursos/edit.html.haml
%h1 Editing Materia en Curso

= render 'form'

= link_to 'Show', @materia_curso
\|
= link_to 'Back', materia_cursos_path

app/views/materia_cursos/index.html.haml
%h1 Listing Materias en Curso

%table
  %tr
    %th Materium
    %th Curso
    %th
    %th
    %th

  - @materia_cursos.each do |materia_curso|
    %tr
      %td= materia_curso.materium.nombre
      %td= materia_curso.curso.nombre
      %td= link_to 'Show', materia_curso
      %td= link_to 'Edit', edit_materia_curso_path(materia_curso)
      %td= link_to 'Destroy', materia_curso, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Materia curso', new_materia_curso_path

app/views/materia_cursos/new.html.haml
%h1 New Materia en Curso

= render 'form'

= link_to 'Back', materia_cursos_path

app/views/materia_cursos/show.html.haml
%p#notice= notice

%p
  %b Materium:
  = @materia_curso.materium_id
%p
  %b Curso:
  = @materia_curso.curso_id

= link_to 'Edit', edit_materia_curso_path(@materia_curso)
\|
= link_to 'Back', materia_cursos_path