config/routes.rb
Sigco::Application.routes.draw do
  
  resources :materiales_auditoria

  resources :auditoria

  resources :auditors

  resources :visita

  resources :materials

  resources :inscripcions

  resources :materia_cursos

  resources :profesors

  resources :materia

  resources :cursos

  resources :administradors

  resources :fichas

  root 'vecinos#index'

  resources :vecinos

  get 'facturas' => 'facturas#index'
  get 'facturas/create' => 'facturas#new'
  get 'facturas/:id' => 'facturas#show', :as => :factura
  post 'facturas' => 'facturas#create'

end

app/models/administrador.rb
class Administrador < ActiveRecord::Base

	validates_presence_of :nombre

	has_many :fichas

end

app/models/auditor.rb
class Auditor < ActiveRecord::Base
	validates_presence_of :nombre
    validates_presence_of :apellidos
    validates_presence_of :cif
    validates_presence_of :nombre_empresa
    validates_presence_of :direccion_empresa
    validates_presence_of :telefono

    has_many :auditoria

end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base
	belongs_to :auditor

end

app/models/curso.rb
class Curso < ActiveRecord::Base

	has_many :materia_curso
	has_many :materia, :through => :materia_curso

	has_many :inscripcion
	has_many :vecinos, :through => :inscripcion

end

app/models/factura.rb
class Factura < ActiveRecord::Base

	has_many :fichas
	belongs_to :vecino

end

app/models/ficha.rb
class Ficha < ActiveRecord::Base

	belongs_to :vecino
	belongs_to :factura
	belongs_to :administrador

end

app/models/inscripcion.rb
class Inscripcion < ActiveRecord::Base
	belongs_to :vecino
	belongs_to :curso
end

app/models/materia_curso.rb
class MateriaCurso < ActiveRecord::Base

	belongs_to :materium
	belongs_to :curso

end

app/models/material.rb
class Material < ActiveRecord::Base
	
end

app/models/materium.rb
class Materium < ActiveRecord::Base

	has_many :materia_cursos
	has_many :cursos, :through => :materia_cursos
	belongs_to :profesor

end

app/models/profesor.rb
class Profesor < ActiveRecord::Base

	has_many :materias

	def nombre_completo
		self.nombre + ' ' + self.apellidos
	end

end

app/models/vecino.rb
class Vecino < ActiveRecord::Base

	validates_presence_of :DNI
	validates_presence_of :nombre
	validates_presence_of :apellidos
	validates_presence_of :direccion
	validates_presence_of :ciudad
	validates_presence_of :cod_postal
	validates_presence_of :telefono

	has_many :facturas
	has_many :fichas

	has_many :inscripcion
	has_many :cursos, :through => :inscripcion

	# Methods
	
	def nombre_completo
		self.nombre + ' ' + self.apellidos
	end

end

app/models/visitum.rb
class Visitum < ActiveRecord::Base

	belongs_to :auditor

end

app/controllers/auditors_controller.rb
class AuditorsController < ApplicationController
  before_action :set_auditor, only: [:show, :edit, :update, :destroy]

  # GET /auditors
  # GET /auditors.json
  def index
    @auditors = Auditor.all
  end

  # GET /auditors/1
  # GET /auditors/1.json
  def show
  end

  # GET /auditors/new
  def new
    @auditor = Auditor.new
  end

  # GET /auditors/1/edit
  def edit
  end

  # POST /auditors
  # POST /auditors.json
  def create
    @auditor = Auditor.new(auditor_params)

    respond_to do |format|
      if @auditor.save
        format.html { redirect_to @auditor, notice: 'Auditor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @auditor }
      else
        format.html { render action: 'new' }
        format.json { render json: @auditor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auditors/1
  # PATCH/PUT /auditors/1.json
  def update
    respond_to do |format|
      if @auditor.update(auditor_params)
        format.html { redirect_to @auditor, notice: 'Auditor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @auditor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auditors/1
  # DELETE /auditors/1.json
  def destroy
    @auditor.destroy
    respond_to do |format|
      format.html { redirect_to auditors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auditor
      @auditor = Auditor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auditor_params
      params.require(:auditor).permit(:nombre, :apellidos, :cif, :nombre_empresa, :direccion_empresa, :telefono)
    end
end

app/helpers/auditoria_helper.rb
module AuditoriaHelper
end

app/helpers/auditors_helper.rb
module AuditorsHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/vecinos_helper.rb
module VecinosHelper
end

app/helpers/visita_helper.rb
module VisitaHelper
end

app/views/auditors/_form.html.haml
= form_for @auditor do |f|
  - if @auditor.errors.any?
    #error_explanation
      %h2= "#{pluralize(@auditor.errors.count, "error")} prohibited this auditor from being saved:"
      %ul
        - @auditor.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :nombre
    = f.text_field :nombre
  .field
    = f.label :apellidos
    = f.text_field :apellidos
  .field
    = f.label :cif
    = f.text_field :cif
  .field
    = f.label :nombre_empresa
    = f.text_field :nombre_empresa
  .field
    = f.label :direccion_empresa
    = f.text_field :direccion_empresa
  .field
    = f.label :telefono
    = f.text_field :telefono
  .actions
    = f.submit 'Save'

app/views/auditors/edit.html.haml
%h1 Editing auditor

= render 'form'

= link_to 'Show', @auditor
\|
= link_to 'Back', auditors_path

app/views/auditors/index.html.haml
%h1 Listing auditors

%table
  %tr
    %th Nombre
    %th Apellidos
    %th Cif
    %th Nombre empresa
    %th Direccion empresa
    %th Telefono
    %th
    %th
    %th

  - @auditors.each do |auditor|
    %tr
      %td= auditor.nombre
      %td= auditor.apellidos
      %td= auditor.cif
      %td= auditor.nombre_empresa
      %td= auditor.direccion_empresa
      %td= auditor.telefono
      %td= link_to 'Show', auditor
      %td= link_to 'Edit', edit_auditor_path(auditor)
      %td= link_to 'Destroy', auditor, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Auditor', new_auditor_path

app/views/auditors/new.html.haml
%h1 New auditor

= render 'form'

= link_to 'Back', auditors_path

app/views/auditors/show.html.haml
%p#notice= notice

%p
  %b Nombre:
  = @auditor.nombre
%p
  %b Apellidos:
  = @auditor.apellidos
%p
  %b Cif:
  = @auditor.cif
%p
  %b Nombre empresa:
  = @auditor.nombre_empresa
%p
  %b Direccion empresa:
  = @auditor.direccion_empresa
%p
  %b Telefono:
  = @auditor.telefono

= link_to 'Edit', edit_auditor_path(@auditor)
\|
= link_to 'Back', auditors_path