config/routes.rb
Sigco::Application.routes.draw do
  
  resources :materiales_auditoria

  resources :auditoria

  resources :auditors

  resources :visita

  resources :materials

  resources :inscripcions

  resources :materia_cursos

  resources :profesors

  resources :materia

  resources :cursos

  resources :administradors

  resources :fichas

  root 'vecinos#index'

  resources :vecinos

  get 'facturas' => 'facturas#index'
  get 'facturas/create' => 'facturas#new'
  get 'facturas/:id' => 'facturas#show', :as => :factura
  post 'facturas' => 'facturas#create'

end

app/models/administrador.rb
class Administrador < ActiveRecord::Base

	validates_presence_of :nombre

	has_many :fichas

end

app/models/auditor.rb
class Auditor < ActiveRecord::Base
	validates_presence_of :nombre
    validates_presence_of :apellidos
    validates_presence_of :cif
    validates_presence_of :nombre_empresa
    validates_presence_of :direccion_empresa
    validates_presence_of :telefono

    has_many :auditoria

end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base
	belongs_to :auditor

end

app/models/curso.rb
class Curso < ActiveRecord::Base

	has_many :materia_curso
	has_many :materia, :through => :materia_curso

	has_many :inscripcion
	has_many :vecinos, :through => :inscripcion

end

app/models/factura.rb
class Factura < ActiveRecord::Base

	has_many :fichas
	belongs_to :vecino

end

app/models/ficha.rb
class Ficha < ActiveRecord::Base

	belongs_to :vecino
	belongs_to :factura
	belongs_to :administrador

end

app/models/inscripcion.rb
class Inscripcion < ActiveRecord::Base
	belongs_to :vecino
	belongs_to :curso
end

app/models/materia_curso.rb
class MateriaCurso < ActiveRecord::Base

	belongs_to :materium
	belongs_to :curso

end

app/models/material.rb
class Material < ActiveRecord::Base
	
end

app/models/materium.rb
class Materium < ActiveRecord::Base

	has_many :materia_cursos
	has_many :cursos, :through => :materia_cursos
	belongs_to :profesor

end

app/models/profesor.rb
class Profesor < ActiveRecord::Base

	has_many :materias

	def nombre_completo
		self.nombre + ' ' + self.apellidos
	end

end

app/models/vecino.rb
class Vecino < ActiveRecord::Base

	validates_presence_of :DNI
	validates_presence_of :nombre
	validates_presence_of :apellidos
	validates_presence_of :direccion
	validates_presence_of :ciudad
	validates_presence_of :cod_postal
	validates_presence_of :telefono

	has_many :facturas
	has_many :fichas

	has_many :inscripcion
	has_many :cursos, :through => :inscripcion

	# Methods
	
	def nombre_completo
		self.nombre + ' ' + self.apellidos
	end

end

app/models/visitum.rb
class Visitum < ActiveRecord::Base

	belongs_to :auditor

end

app/controllers/fichas_controller.rb
class FichasController < ApplicationController
  before_action :set_ficha, only: [:show, :edit, :update, :destroy]

  # GET /fichas
  # GET /fichas.json
  def index
    @fichas = Ficha.all
  end

  # GET /fichas/1
  # GET /fichas/1.json
  def show
  end

  # GET /fichas/new
  def new
    @ficha = Ficha.new
  end

  # GET /fichas/1/edit
  def edit
  end

  # POST /fichas
  # POST /fichas.json
  def create
    @ficha = Ficha.new(ficha_params)

    respond_to do |format|
      if @ficha.save
        format.html { redirect_to @ficha, notice: 'Ficha was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ficha }
      else
        format.html { render action: 'new' }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fichas/1
  # PATCH/PUT /fichas/1.json
  def update
    respond_to do |format|
      if @ficha.update(ficha_params)
        format.html { redirect_to @ficha, notice: 'Ficha was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fichas/1
  # DELETE /fichas/1.json
  def destroy
    @ficha.destroy
    respond_to do |format|
      format.html { redirect_to fichas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ficha
      @ficha = Ficha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ficha_params
      params.require(:ficha).permit(:vecino_id, :administrador_id, :fecha, :descripcion, :importe, :pagada)
    end
end

app/helpers/auditoria_helper.rb
module AuditoriaHelper
end

app/helpers/auditors_helper.rb
module AuditorsHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/materia_helper.rb
module MateriaHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/vecinos_helper.rb
module VecinosHelper
end

app/helpers/visita_helper.rb
module VisitaHelper
end

app/views/fichas/_form.html.haml
= form_for @ficha do |f|
  - if @ficha.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ficha.errors.count, "error")} prohibited this ficha from being saved:"
      %ul
        - @ficha.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :vecino
    = f.collection_select :vecino_id, Vecino.all, :id, :nombre
  .field
    = f.label :administrador
    = f.collection_select :administrador_id, Administrador.all, :id, :nombre
  .field
    = f.label :fecha
    = f.date_select :fecha
  .field
    = f.label :descripcion
    = f.text_field :descripcion
  .field
    = f.label :importe
    = f.text_field :importe
  .actions
    = f.submit 'Save'

app/views/fichas/edit.html.haml
%h1 Editing ficha

= render 'form'

= link_to 'Show', @ficha
\|
= link_to 'Back', fichas_path

app/views/fichas/index.html.haml
%h1 Listing fichas

%table
  %tr
    %th Vecino
    %th Administrador
    %th Fecha
    %th Descripcion
    %th Importe
    %th Pagada
    %th
    %th
    %th

  - @fichas.each do |ficha|
    %tr
      %td= ficha.vecino.nombre
      %td= ficha.administrador.nombre
      %td= l(ficha.fecha, :format => :short)
      %td= ficha.descripcion
      %td= ficha.importe
      %td= raw(ficha.pagada ? '<span class="label label-success">Pagada</span>' : '<span class="label label-warning">Pendiente</span>')
      %td= link_to 'Show', ficha
      %td= link_to 'Edit', edit_ficha_path(ficha)
      %td= link_to 'Destroy', ficha, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Ficha', new_ficha_path

app/views/fichas/new.html.haml
%h1 New ficha

= render 'form'

= link_to 'Back', fichas_path

app/views/fichas/show.html.haml
%p#notice= notice

%p
  %b Vecino:
  = @ficha.vecino_id
%p
  %b Administrador:
  = @ficha.administrador_id
%p
  %b Fecha:
  = l(@ficha.fecha, :format => :short)
%p
  %b Descripcion:
  = @ficha.descripcion
%p
  %b Importe:
  = @ficha.importe
%p
  %b Pagada:
  = @ficha.pagada

= link_to 'Edit', edit_ficha_path(@ficha)
\|
= link_to 'Back', fichas_path